version: '3.8'
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      # Mount the host’s private‑key.pem into /app/config/private-key.pem inside the container
      - ./pga-github-app.2025-03-25.private-key.pem:/app/config/private-key.pem:ro
    environment:
      - PRIVATE_KEY_PATH=/app/config/private-key.pem
    depends_on:
      - graph
  graph:
    image: zepai/graphiti:latest
    ports:
      - "8000:8000"
    env_file: .env.graphiti
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:5.22.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
       - NEO4J_AUTH=neo4j/password
      # - NEO4J_AUTH=none
volumes:
  neo4j_data:
